### ISSUE TITLE
Lon subject not showing after a recent change

### ISSUE THREAD

**Issue by medoix** [grant-olson/BitMessageForum#54]
After latest pull a conversation in the General chan with the subject of RE: RE: RE: RE: RE: and so on now shows no subject.
![screen shot 2013-08-09 at 1 31 18 pm](https://f.cloud.github.com/assets/149519/936218/f4bbc9a6-00a4-11e3-97fa-494fc050dc0f.png)

**Comment by grant-olson** [comment]
I updated the thread compacting code.  Before we would properly put "Re: Subject" in the "Subject" thread, but not "Re: Re: Subject".  That would fork into a new thread.  So I updated the code to account for that.  Since this message just had "Re: Re: ..." With no actual subject, it got abbreviated to to a message with no subject.

In this case the RE:s actually were the subject, but I'm not sure what to do about it.  I can't just assume that if I can't find an existing subject, this is a new subject containing RE:s only, because messages can arrive out-of-order from when they were sent.  That is, I can get "RE: subject" before I get "subject"

I'm not sure what a good fix here is.  If you have any ideas, let me know.

**Comment by medoix** [comment]
Maybe just a regex so check anything after the last RE:/Re: and if nothing maybe set a subject of "No Subject" or something?

**Comment by grant-olson** [comment]
I don't want to rewrite the subject as "No Subject" because that will show up as the subject if you reply.

However, if the issue is that there's nothing to click on, take a look at line 28 of threads.haml.  That plugs in a blank space so that there's a link to click on.  If you want to change that to display "(no subject)", particularly in a way that is styled differently than a real subject, go for it.

**Comment by grant-olson** [comment]
And add a similar fix with similar styling at line 11 of messages.haml.  If the thread == " ", etc.

**Comment by medoix** [comment]
Fixed.
