### ISSUE TITLE
Reply Chan / Reply User Buttons

### ISSUE THREAD

**Issue by medoix** [grant-olson/BitMessageForum#59]
Not sure how this "should" work or maybe it is just me who is wrong but when i select "Reply Chan" i expect to be anon and the compose form should default the from field to the channel instead of my primary identity.

I understand this in direct messages as it is needed but in chans maybe default reply from the channel itself.

**Comment by grant-olson** [comment]
I consider this a feature not a bug.  I personally don't like the default anonymous behavior on chans.

From what other people are saying, they only post anonymously because if they don't then they get personal replies due to the current UI in PyBitmessage.  This issue is open in PyBitmessage: Bitmessage/PyBitmessage#392 .

Lets leave the issue open so people can vote either way.

**Comment by medoix** [comment]
I see both sides of this. Maybe make an option to  reply as default address or reply as chan to chans...

**Comment by Atheros1** [comment]
This has been changed in Bitmessage: The reply to a message sent to a chan address will now be addressed to the same chan address.
